# Generated by Django 5.1.15 on 2025-12-26 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("systems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DFDTemplatesLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("webapp", "Web Application"),
                            ("microservices", "Microservices"),
                            ("iot", "IoT"),
                            ("api", "API"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "diagram_type",
                    models.CharField(
                        choices=[
                            ("context", "Context"),
                            ("level1", "Level 1"),
                            ("level2", "Level 2"),
                        ],
                        max_length=20,
                    ),
                ),
                ("canvas_data", models.JSONField(blank=True, default=dict)),
                (
                    "maintained_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintained_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means global/shared",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dfd_templates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DFD templates library",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="DFD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "diagram_type",
                    models.CharField(
                        choices=[
                            ("context", "Context"),
                            ("level1", "Level 1"),
                            ("level2", "Level 2"),
                        ],
                        default="level1",
                        max_length=20,
                    ),
                ),
                ("canvas_data", models.JSONField(blank=True, default=dict)),
                ("threat_analysis_data", models.JSONField(blank=True, default=dict)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_dfds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instantiated_dfds",
                        to="diagrams.dfdtemplateslibrary",
                    ),
                ),
            ],
            options={
                "verbose_name": "DFD",
                "verbose_name_plural": "DFDs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ThreatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("new", "New System"),
                            ("incident", "Security Incident"),
                            ("pentest", "Penetration Test"),
                            ("drift", "Architecture Drift"),
                            ("feature_addition", "Feature Addition"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("workspace_data", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_threat_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_models",
                        to="organizations.organization",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="diagrams.threatmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DFDOrgsystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dfd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orgsystem_associations",
                        to="diagrams.dfd",
                    ),
                ),
                (
                    "orgsystem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dfd_associations",
                        to="systems.orgsystem",
                    ),
                ),
            ],
            options={
                "unique_together": {("dfd", "orgsystem")},
            },
        ),
        migrations.CreateModel(
            name="ThreatModelDFD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dfd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_model_associations",
                        to="diagrams.dfd",
                    ),
                ),
                (
                    "threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dfd_associations",
                        to="diagrams.threatmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("threat_model", "dfd")},
            },
        ),
        migrations.CreateModel(
            name="ThreatModelOrgsystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orgsystem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_model_associations",
                        to="systems.orgsystem",
                    ),
                ),
                (
                    "threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orgsystem_associations",
                        to="diagrams.threatmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("threat_model", "orgsystem")},
            },
        ),
        migrations.CreateModel(
            name="ThreatModelRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("depends_on", "Depends On"),
                            ("subsystem_of", "Subsystem Of"),
                            ("related_to", "Related To"),
                            ("superseded_by", "Superseded By"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="diagrams.threatmodel",
                    ),
                ),
                (
                    "target_threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="diagrams.threatmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("source_threat_model", "target_threat_model", "relation_type")
                },
            },
        ),
    ]
