# Generated by Django 5.1.15 on 2026-03-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('diagram_type', models.CharField(choices=[('context', 'Context'), ('level1', 'Level 1'), ('level2', 'Level 2')], default='level1', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Only the primary DFD syncs nodes to components/threats.')),
                ('canvas_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'DFD',
                'verbose_name_plural': 'DFDs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DFDTemplatesLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text="Unique identifier within pack, e.g., 'banking-webapp-l1'", max_length=100)),
                ('qualified_slug', models.CharField(blank=True, db_index=True, help_text="Namespace-safe identifier, e.g., 'banking-templates/webapp-l1'", max_length=200, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(help_text='Freeform category (e.g., webapp, serverless, microservices)', max_length=50)),
                ('diagram_type', models.CharField(choices=[('context', 'Context'), ('level1', 'Level 1'), ('level2', 'Level 2')], max_length=20)),
                ('canvas_data', models.JSONField(blank=True, default=dict)),
                ('customization_status', models.CharField(choices=[('original', 'Original (from pack)'), ('customized', 'Customized (user edited)'), ('detached', 'Detached (unlinked from pack)')], default='original', max_length=20)),
                ('base_item_qualified_slug', models.CharField(blank=True, db_index=True, help_text='Original item this was forked/customized from', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'DFD templates library',
                'ordering': ['category', 'name'],
            },
        ),
    ]
