# Generated by Django 5.1.15 on 2026-03-22 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagrams', '0001_initial'),
        ('packs', '0001_initial'),
        ('threat_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dfd',
            name='threat_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dfds', to='threat_models.threatmodel'),
        ),
        migrations.AddField(
            model_name='dfd',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dfds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dfdtemplateslibrary',
            name='maintained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dfdtemplateslibrary',
            name='source_pack',
            field=models.ForeignKey(blank=True, help_text='Pack this item came from (null = custom or legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfd_templates', to='packs.librarypack'),
        ),
        migrations.AddField(
            model_name='dfd',
            name='template_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instantiated_dfds', to='diagrams.dfdtemplateslibrary'),
        ),
        migrations.AddConstraint(
            model_name='dfdtemplateslibrary',
            constraint=models.UniqueConstraint(fields=('qualified_slug',), name='unique_dfdtemplate_qualified_slug'),
        ),
        migrations.AddConstraint(
            model_name='dfd',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('threat_model',), name='unique_primary_dfd_per_threat_model'),
        ),
    ]
