# Generated by Django 5.1.15 on 2025-12-27 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0001_initial"),
        ("packs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dfdtemplateslibrary",
            name="source_pack",
            field=models.ForeignKey(
                blank=True,
                help_text="Pack this item came from (null = custom or legacy)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dfd_templates",
                to="packs.librarypack",
            ),
        ),
    ]
