# Generated by Django 5.1.15 on 2026-01-27 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance", "0002_initial"),
        ("diagrams", "0001_initial"),
        ("organizations", "0001_initial"),
        ("packs", "0001_initial"),
        ("systems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dfdorgsystem",
            name="orgsystem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dfd_associations",
                to="systems.orgsystem",
            ),
        ),
        migrations.AddField(
            model_name="dfdtemplateslibrary",
            name="maintained_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintained_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dfdtemplateslibrary",
            name="source_pack",
            field=models.ForeignKey(
                blank=True,
                help_text="Pack this item came from (null = custom or legacy)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dfd_templates",
                to="packs.librarypack",
            ),
        ),
        migrations.AddField(
            model_name="dfd",
            name="template_library",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instantiated_dfds",
                to="diagrams.dfdtemplateslibrary",
            ),
        ),
        migrations.AddField(
            model_name="threatmodel",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_threat_models",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="threatmodel",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_models",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="threatmodel",
            name="owning_team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team that owns this threat model (nullable during migration)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="threat_models",
                to="organizations.team",
            ),
        ),
        migrations.AddField(
            model_name="threatmodel",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_versions",
                to="diagrams.threatmodel",
            ),
        ),
        migrations.AddField(
            model_name="threatmodeldfd",
            name="dfd",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_model_associations",
                to="diagrams.dfd",
            ),
        ),
        migrations.AddField(
            model_name="threatmodeldfd",
            name="threat_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dfd_associations",
                to="diagrams.threatmodel",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelframework",
            name="framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_model_associations",
                to="compliance.standardframework",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelframework",
            name="threat_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="framework_associations",
                to="diagrams.threatmodel",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelorgsystem",
            name="orgsystem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_model_associations",
                to="systems.orgsystem",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelorgsystem",
            name="threat_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orgsystem_associations",
                to="diagrams.threatmodel",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelrelationship",
            name="source_threat_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_relationships",
                to="diagrams.threatmodel",
            ),
        ),
        migrations.AddField(
            model_name="threatmodelrelationship",
            name="target_threat_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_relationships",
                to="diagrams.threatmodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dfdorgsystem",
            unique_together={("dfd", "orgsystem")},
        ),
        migrations.AddConstraint(
            model_name="dfdtemplateslibrary",
            constraint=models.UniqueConstraint(
                fields=("qualified_slug",), name="unique_dfdtemplate_qualified_slug"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="threatmodeldfd",
            unique_together={("threat_model", "dfd")},
        ),
        migrations.AlterUniqueTogether(
            name="threatmodelframework",
            unique_together={("threat_model", "framework")},
        ),
        migrations.AlterUniqueTogether(
            name="threatmodelorgsystem",
            unique_together={("threat_model", "orgsystem")},
        ),
        migrations.AlterUniqueTogether(
            name="threatmodelrelationship",
            unique_together={
                ("source_threat_model", "target_threat_model", "relation_type")
            },
        ),
    ]
