# Generated by Django 5.1.15 on 2026-03-01 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagrams', '0001_initial'),
        ('packs', '0001_initial'),
        ('systems', '0001_initial'),
        ('threat_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dfdorgsystem',
            name='orgsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfd_associations', to='systems.orgsystem'),
        ),
        migrations.AddField(
            model_name='dfdtemplateslibrary',
            name='maintained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dfdtemplateslibrary',
            name='source_pack',
            field=models.ForeignKey(blank=True, help_text='Pack this item came from (null = custom or legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfd_templates', to='packs.librarypack'),
        ),
        migrations.AddField(
            model_name='dfd',
            name='template_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instantiated_dfds', to='diagrams.dfdtemplateslibrary'),
        ),
        migrations.AddField(
            model_name='threatmodeldfd',
            name='dfd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_model_associations', to='diagrams.dfd'),
        ),
        migrations.AddField(
            model_name='threatmodeldfd',
            name='threat_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfd_associations', to='threat_models.threatmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='dfdorgsystem',
            unique_together={('dfd', 'orgsystem')},
        ),
        migrations.AddConstraint(
            model_name='dfdtemplateslibrary',
            constraint=models.UniqueConstraint(fields=('qualified_slug',), name='unique_dfdtemplate_qualified_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='threatmodeldfd',
            unique_together={('threat_model', 'dfd')},
        ),
    ]
