# Generated by Django 5.1.15 on 2026-02-05 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="threatmodel",
            name="modeling_mode",
            field=models.CharField(
                choices=[
                    ("dfdBased", "DFD-Based"),
                    ("manual", "Manual Entry"),
                    ("hybrid", "Hybrid (Both)"),
                ],
                default="dfdBased",
                help_text="Primary threat modeling approach for this model",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ThreatModelReferenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Reference image file (JPEG, PNG, WebP)",
                        upload_to="reference_images/%Y/%m/",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original filename for display", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this image shows",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in gallery (lower = first)"
                    ),
                ),
                (
                    "threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_images",
                        to="diagrams.threatmodel",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_reference_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
