# Generated by Django 5.1.15 on 2025-12-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0002_dfdtemplateslibrary_source_pack"),
    ]

    operations = [
        migrations.AddField(
            model_name="dfdtemplateslibrary",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique identifier for pack references, e.g., 'banking-webapp-l1'",
                max_length=100,
            ),
        ),
    ]
