# Generated by Django 5.1.15 on 2026-03-15 07:19

from django.conf import settings
from django.db import migrations, models


def set_first_dfd_as_primary(apps, schema_editor):
    """For each threat model, mark the earliest DFD as primary."""
    DFD = apps.get_model("diagrams", "DFD")
    from django.db.models import Min

    threat_model_ids = (
        DFD.objects.filter(threat_model__isnull=False)
        .values("threat_model_id")
        .annotate(first_dfd=Min("id"))
    )
    first_dfd_ids = [entry["first_dfd"] for entry in threat_model_ids]
    DFD.objects.filter(id__in=first_dfd_ids).update(is_primary=True)


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0003_one_dfd_per_threat_model"),
        ("threat_models", "0006_remove_threatmodel_previous_version_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dfd",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Only the primary DFD syncs nodes to components/threats.",
            ),
        ),
        migrations.RunPython(
            set_first_dfd_as_primary,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="dfd",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("threat_model",),
                name="unique_primary_dfd_per_threat_model",
            ),
        ),
    ]
