# Generated by Django 5.1.15 on 2025-12-27 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0004_reviewer_feedback_fixes"),
        ("organizations", "0001_initial"),
        ("packs", "0002_reviewer_feedback_fixes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dfdtemplateslibrary",
            name="base_item_qualified_slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Original item this was forked/customized from",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="dfdtemplateslibrary",
            name="qualified_slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Namespace-safe identifier, e.g., 'banking-templates/webapp-l1'",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="dfdtemplateslibrary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("qualified_slug",),
                name="unique_active_dfdtemplate_qualified_slug",
            ),
        ),
    ]
