# Generated by Django 5.1.15 on 2026-03-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0004_add_is_primary_to_dfd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dfd",
            name="threat_analysis_data",
        ),
    ]
