# Generated by Django 5.1.15 on 2026-03-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0005_remove_dfdtemplateslibrary_category_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatmodel',
            name='risk_scoring_method',
            field=models.CharField(choices=[('tm_library', 'Likelihood x Impact (5x5 Matrix)'), ('fair', 'FAIR'), ('owasp_rr', 'OWASP Risk Rating'), ('mozilla_rra', 'Mozilla Rapid Risk Assessment'), ('custom', 'Manual Score')], default='tm_library', help_text='Scoring methodology used for all risks in this threat model', max_length=20),
        ),
    ]
