# Generated by Django 5.1.15 on 2025-12-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
        ("diagrams", "0005_zombie_record_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatmodel",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ThreatModelFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_model_associations",
                        to="compliance.standardframework",
                    ),
                ),
                (
                    "threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="framework_associations",
                        to="diagrams.threatmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("threat_model", "framework")},
            },
        ),
    ]
