# Generated by Django 5.1.15 on 2025-12-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0006_threatmodel_criticality_threatmodelframework"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threatmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("inProgress", "In Progress"),
                    ("pendingReview", "Pending Review"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
