# Generated by Django 5.1.15 on 2026-01-18 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0007_alter_threatmodel_status"),
        (
            "organizations",
            "0002_organization_business_unit_label_businessunit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="threatmodel",
            name="owning_team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team that owns this threat model (nullable during migration)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="threat_models",
                to="organizations.team",
            ),
        ),
    ]
