# Generated by Django 5.1.15 on 2026-03-22 02:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentDataAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_state', models.CharField(choices=[('at_rest', 'At Rest'), ('processed', 'Processed')], default='processed', max_length=20)),
                ('volume', models.CharField(blank=True, max_length=100)),
                ('encrypted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('classification', models.CharField(max_length=100)),
                ('confidentiality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('integrity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('availability', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('compliance_tags', models.JSONField(blank=True, default=list)),
                ('data_sensitivity', models.JSONField(blank=True, default=list)),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text='Display label for the data flow', max_length=255)),
                ('edge_id', models.CharField(blank=True, db_index=True, help_text='DFD edge ID this flow was created from', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('protocol', models.CharField(blank=True, max_length=50)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('encrypted', models.BooleanField(default=False)),
                ('authenticated', models.BooleanField(default=False)),
                ('crosses_trust_zone', models.BooleanField(default=False)),
                ('has_sensitive_data', models.BooleanField(default=False)),
                ('data_classification', models.JSONField(blank=True, default=list)),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['source_component', 'dest_component'],
            },
        ),
        migrations.CreateModel(
            name='DataFlowAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protection_method', models.CharField(choices=[('encrypted', 'Encrypted'), ('masked', 'Masked'), ('tokenized', 'Tokenized'), ('hashed', 'Hashed'), ('none', 'None')], default='none', max_length=20)),
                ('encryption_type', models.CharField(blank=True, max_length=50)),
                ('format', models.CharField(blank=True, max_length=50)),
                ('sensitivity_override', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('github', 'GitHub'), ('cspm', 'CSPM'), ('terraform', 'Terraform'), ('sbom', 'SBOM'), ('manual', 'Manual')], max_length=20)),
                ('connection_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Orgsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('lifecycle_state', models.CharField(choices=[('development', 'Development'), ('production', 'Production'), ('decommissioned', 'Decommissioned')], default='development', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgsystemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('actor_type', models.CharField(blank=True, default='', max_length=20)),
                ('data_store_type', models.CharField(blank=True, default='', max_length=20)),
                ('data_sensitivity_level', models.CharField(blank=True, default='', max_length=20)),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(blank=True, help_text='Copied from ComponentLibrary.category on creation', max_length=20)),
                ('component_type', models.CharField(blank=True, help_text='Copied from ComponentLibrary.component_type on creation', max_length=100)),
                ('provider', models.CharField(blank=True, help_text='Copied from ComponentLibrary.provider on creation', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrustBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('edge_id', models.CharField(blank=True, db_index=True, help_text='DFD edge ID this boundary was created from', max_length=100)),
                ('format_metadata', models.JSONField(blank=True, default=dict, help_text='Auth methods, access control, token TTL, etc.')),
            ],
            options={
                'verbose_name_plural': 'Trust boundaries',
                'ordering': ['zone_a', 'zone_b'],
            },
        ),
        migrations.CreateModel(
            name='TrustZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('trust_level', models.IntegerField(default=50, help_text='0-100 scale')),
                ('description', models.TextField(blank=True)),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Trust zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text="Unique identifier within pack, e.g., 'aws-s3'", max_length=100)),
                ('qualified_slug', models.CharField(blank=True, db_index=True, help_text="Namespace-safe identifier, e.g., 'aws-technologies/s3'", max_length=200, null=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('process', 'Process'), ('datastore', 'Data Store'), ('external', 'External Entity'), ('human_actor', 'Human Actor'), ('system_actor', 'System Actor')], max_length=20)),
                ('component_type', models.CharField(max_length=100)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('customization_status', models.CharField(choices=[('original', 'Original (from pack)'), ('customized', 'Customized (user edited)'), ('detached', 'Detached (unlinked from pack)')], default='original', max_length=20)),
                ('base_item_qualified_slug', models.CharField(blank=True, db_index=True, help_text='Original item this was forked/customized from', max_length=200)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Previous slugs for backward compatibility', size=None)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent component in hierarchy (process category only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='systems.componentlibrary')),
                ('source_pack', models.ForeignKey(blank=True, help_text='Pack this item came from (null = custom or legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='packs.librarypack')),
            ],
            options={
                'verbose_name_plural': 'Component libraries',
                'ordering': ['name'],
            },
        ),
    ]
