# Generated by Django 5.1.15 on 2025-12-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("classification", models.CharField(max_length=100)),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "integrity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("compliance_tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComponentLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("process", "Process"),
                            ("datastore", "Data Store"),
                            ("external", "External Entity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("component_type", models.CharField(max_length=100)),
                ("provider", models.CharField(blank=True, max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means global/shared",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_library",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Component libraries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Orgsystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("owner", models.CharField(blank=True, max_length=255)),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("production", "Production"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="development",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orgsystems",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("cspm", "CSPM"),
                            ("terraform", "Terraform"),
                            ("sbom", "SBOM"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("connection_details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "orgsystem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_sources",
                        to="systems.orgsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrgsystemComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "component_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="systems.componentlibrary",
                    ),
                ),
                (
                    "orgsystem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="systems.orgsystem",
                    ),
                ),
                (
                    "source_integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovered_components",
                        to="systems.integrationsource",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("protocol", models.CharField(blank=True, max_length=50)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("crosses_trust_boundary", models.BooleanField(default=False)),
                (
                    "dest_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_flows",
                        to="systems.orgsystemcomponent",
                    ),
                ),
                (
                    "source_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_flows",
                        to="systems.orgsystemcomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["source_component", "dest_component"],
            },
        ),
        migrations.CreateModel(
            name="TrustBoundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "trust_level",
                    models.IntegerField(default=50, help_text="0-100 scale"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="systems.trustboundary",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trust boundaries",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="orgsystemcomponent",
            name="trust_boundary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="systems.trustboundary",
            ),
        ),
        migrations.CreateModel(
            name="DataFlowAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "protection_method",
                    models.CharField(
                        choices=[
                            ("encrypted", "Encrypted"),
                            ("masked", "Masked"),
                            ("tokenized", "Tokenized"),
                            ("hashed", "Hashed"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("encryption_type", models.CharField(blank=True, max_length=50)),
                ("format", models.CharField(blank=True, max_length=50)),
                ("sensitivity_override", models.CharField(blank=True, max_length=20)),
                (
                    "data_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_associations",
                        to="systems.dataasset",
                    ),
                ),
                (
                    "data_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="systems.dataflow",
                    ),
                ),
            ],
            options={
                "unique_together": {("data_flow", "data_asset")},
            },
        ),
        migrations.CreateModel(
            name="ComponentDataAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_state",
                    models.CharField(
                        choices=[("at_rest", "At Rest"), ("processed", "Processed")],
                        default="processed",
                        max_length=20,
                    ),
                ),
                ("volume", models.CharField(blank=True, max_length=100)),
                (
                    "data_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_associations",
                        to="systems.dataasset",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_assets",
                        to="systems.orgsystemcomponent",
                    ),
                ),
            ],
            options={
                "unique_together": {("component", "data_asset")},
            },
        ),
    ]
