# Generated by Django 5.1.15 on 2026-01-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentlibrary",
            name="category",
            field=models.CharField(
                choices=[
                    ("process", "Process"),
                    ("datastore", "Data Store"),
                    ("external", "External Entity"),
                    ("human_actor", "Human Actor"),
                    ("system_actor", "System Actor"),
                ],
                max_length=20,
            ),
        ),
    ]
