# Generated by Django 5.1.15 on 2026-03-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
        ('threat_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsystemcomponent',
            name='threat_model',
            field=models.ForeignKey(blank=True, help_text='For analysis-only components not linked to a DFD. Null means linked via DFD sync.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_components', to='threat_models.threatmodel'),
        ),
        migrations.AddField(
            model_name='dataflow',
            name='dest_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='systems.orgsystemcomponent'),
        ),
        migrations.AddField(
            model_name='dataflow',
            name='source_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='systems.orgsystemcomponent'),
        ),
        migrations.AddField(
            model_name='componentdataasset',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_assets', to='systems.orgsystemcomponent'),
        ),
        migrations.AddField(
            model_name='trustzone',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='systems.trustzone'),
        ),
        migrations.AddField(
            model_name='trustboundary',
            name='zone_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries_as_source', to='systems.trustzone'),
        ),
        migrations.AddField(
            model_name='trustboundary',
            name='zone_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries_as_target', to='systems.trustzone'),
        ),
        migrations.AddField(
            model_name='orgsystemcomponent',
            name='trust_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='systems.trustzone'),
        ),
        migrations.AddConstraint(
            model_name='componentlibrary',
            constraint=models.UniqueConstraint(fields=('qualified_slug',), name='unique_component_qualified_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='dataflowasset',
            unique_together={('data_flow', 'data_asset')},
        ),
        migrations.AlterUniqueTogether(
            name='componentdataasset',
            unique_together={('component', 'data_asset')},
        ),
        migrations.AlterUniqueTogether(
            name='trustboundary',
            unique_together={('zone_a', 'zone_b')},
        ),
    ]
