# Generated by Django 5.1.15 on 2025-12-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("systems", "0002_componentlibrary_source_pack"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustboundary",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Null means global/shared boundary",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_boundaries",
                to="organizations.organization",
            ),
        ),
    ]
