# Generated by Django 5.1.15 on 2026-01-30 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0002_initial"),
        ("systems", "0002_add_human_actor_system_actor_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgsystemcomponent",
            name="threat_model",
            field=models.ForeignKey(
                blank=True,
                help_text="For analysis-only components not linked to a DFD. Null means linked via DFD sync.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_components",
                to="diagrams.threatmodel",
            ),
        ),
    ]
