# Generated by Django 5.1.15 on 2026-03-02 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_initial'),
        ('threat_models', '0002_threatmodel_format_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdataasset',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='data_sensitivity',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='threat_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_assets', to='threat_models.threatmodel'),
        ),
        migrations.AddField(
            model_name='dataflow',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dataflow',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dataflow',
            name='has_sensitive_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsystemcomponent',
            name='actor_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orgsystemcomponent',
            name='data_store_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orgsystemcomponent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orgsystemcomponent',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orgsystemcomponent',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='systems.orgsystemcomponent'),
        ),
        migrations.AddField(
            model_name='trustzone',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
