# Generated by Django 5.1.15 on 2025-12-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0003_schema_discrepancy_fixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentlibrary",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique identifier for pack references, e.g., 'aws-s3'",
                max_length=100,
            ),
        ),
    ]
