# Generated by Django 5.1.15 on 2026-03-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_componentdataasset_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsystem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orgsystem',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
