# Generated by Django 5.1.15 on 2026-07-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0003_category_rename_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustboundary",
            name="authentication",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trustboundary",
            name="authorization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trustboundary",
            name="data_validation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trustboundary",
            name="logging",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trustboundary",
            name="monitoring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trustboundary",
            name="rate_limiting",
            field=models.BooleanField(default=False),
        ),
    ]
