# Generated by Django 5.1.15 on 2026-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_orgsystem_description_orgsystem_format_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataflow',
            name='data_classification',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orgsystemcomponent',
            name='data_sensitivity_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
