# Generated by Django 5.1.15 on 2026-02-28 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_rename_trust_boundary_to_trust_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('edge_id', models.CharField(blank=True, db_index=True, help_text='DFD edge ID this boundary was created from', max_length=100)),
                ('format_metadata', models.JSONField(blank=True, default=dict, help_text='Auth methods, access control, token TTL, etc.')),
                ('zone_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries_as_source', to='systems.trustzone')),
                ('zone_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries_as_target', to='systems.trustzone')),
            ],
            options={
                'verbose_name_plural': 'Trust boundaries',
                'ordering': ['zone_a', 'zone_b'],
                'unique_together': {('zone_a', 'zone_b')},
            },
        ),
    ]
