# Generated by Django 5.1.15 on 2026-03-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0005_dataflow_data_classification_component_sensitivity_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentlibrary",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent component in hierarchy (process category only)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="systems.componentlibrary",
            ),
        ),
    ]
