# Generated by Django 5.1.15 on 2026-01-08 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0006_zombie_record_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgsystemcomponent",
            name="orgsystem",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a system. Null means component exists without system assignment.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="systems.orgsystem",
            ),
        ),
    ]
