# Generated by Django 5.1.15 on 2026-01-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0008_cleanup_placeholder_systems"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataflow",
            name="authenticated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="edge_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="DFD edge ID this flow was created from",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="encrypted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="label",
            field=models.CharField(
                blank=True, help_text="Display label for the data flow", max_length=255
            ),
        ),
    ]
