# Generated by Django 5.1.15 on 2025-12-27 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="librarypack",
            name="depends_on",
        ),
        migrations.CreateModel(
            name="LibraryPackDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version_constraint",
                    models.CharField(
                        blank=True,
                        help_text="SemVer constraint, e.g., '^1.0.0', '>=2.0.0', '~1.2.0'",
                        max_length=50,
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False,
                        help_text="Optional dependencies are not required for installation",
                    ),
                ),
                (
                    "depends_on_pack",
                    models.ForeignKey(
                        help_text="The pack being depended upon",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="packs.librarypack",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        help_text="The pack that has the dependency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="packs.librarypack",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pack Dependency",
                "verbose_name_plural": "Pack Dependencies",
                "unique_together": {("pack", "depends_on_pack")},
            },
        ),
    ]
