# Generated by Django 5.1.15 on 2026-04-30 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRequirementOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_framework_slug', models.CharField(help_text='The slug of the source framework (from_requirement side)', max_length=100)),
                ('target_framework_slug', models.CharField(help_text='The slug of the target framework (to_requirement side)', max_length=100)),
                ('overlay_file_name', models.CharField(help_text="Name of the overlay file (e.g., 'requirements-iec-81001-5-1.yaml')", max_length=255)),
                ('overlay_data', models.JSONField(default=dict, help_text='The raw overlay data from the YAML file')),
                ('mapping_count', models.PositiveIntegerField(default=0, help_text='Number of mappings in this overlay')),
                ('pack', models.ForeignKey(help_text='The pack that contains this overlay', on_delete=django.db.models.deletion.CASCADE, related_name='pending_requirement_overlays', to='packs.librarypack')),
            ],
            options={
                'verbose_name': 'Pending Requirement Overlay',
                'verbose_name_plural': 'Pending Requirement Overlays',
                'ordering': ['pack', 'source_framework_slug', 'target_framework_slug'],
                'unique_together': {('pack', 'source_framework_slug', 'target_framework_slug')},
            },
        ),
    ]
