# Generated by Django 5.1.15 on 2026-01-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="librarypack",
            name="owner_organization",
        ),
        migrations.DeleteModel(
            name="OrganizationPackInstallation",
        ),
    ]
