# Generated by Django 5.1.15 on 2026-02-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0002_remove_librarypack_owner_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarypack",
            name="pack_type",
            field=models.CharField(
                choices=[
                    ("technology", "Technology Pack"),
                    ("threat", "Threat Pack"),
                    ("countermeasure", "Countermeasure Pack"),
                    ("compliance", "Compliance Pack"),
                    ("template", "DFD Template Pack"),
                    ("full", "Full Stack Pack"),
                    ("taxonomy", "Taxonomy Pack"),
                ],
                max_length=20,
            ),
        ),
    ]
