# Generated by Django 5.1.15 on 2025-12-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0002_reviewer_feedback_fixes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationpackinstallation",
            name="status",
            field=models.CharField(
                choices=[
                    ("installed", "Installed"),
                    ("pendingUpdate", "Update Available"),
                    ("failed", "Installation Failed"),
                ],
                default="installed",
                max_length=20,
            ),
        ),
    ]
