# Generated by Django 5.1.15 on 2026-03-22 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('organizations', '0001_initial'),
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('modeling_mode', models.CharField(choices=[('dfdBased', 'DFD-Based'), ('manual', 'Manual Entry'), ('hybrid', 'Hybrid (Both)')], default='dfdBased', help_text='Primary threat modeling approach for this model', max_length=20)),
                ('risk_scoring_method', models.CharField(choices=[('tm_library', 'Likelihood x Impact (5x5 Matrix)'), ('fair', 'FAIR'), ('owasp_rr', 'OWASP Risk Rating'), ('mozilla_rra', 'Mozilla Rapid Risk Assessment'), ('custom', 'Manual Score')], default='tm_library', help_text='Scoring methodology used for all risks in this threat model', max_length=20)),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
                ('workspace_data', models.JSONField(blank=True, default=dict)),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('scope_locked', models.BooleanField(default=False)),
                ('scope_locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_threat_models', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_models', to='organizations.organization')),
                ('owning_team', models.ForeignKey(blank=True, help_text='Team that owns this threat model (nullable during migration)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='threat_models', to='organizations.team')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OutOfScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_of_scope_items', to='threat_models.threatmodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThreatModelReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Reference image file (JPEG, PNG, WebP)', upload_to='reference_images/%Y/%m/')),
                ('filename', models.CharField(help_text='Original filename for display', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this image shows')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in gallery (lower = first)')),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='threat_models.threatmodel')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reference_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatModelFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_model_associations', to='compliance.standardframework')),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_associations', to='threat_models.threatmodel')),
            ],
            options={
                'unique_together': {('threat_model', 'framework')},
            },
        ),
        migrations.CreateModel(
            name='ThreatModelOrgsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_model_associations', to='systems.orgsystem')),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgsystem_associations', to='threat_models.threatmodel')),
            ],
            options={
                'unique_together': {('threat_model', 'orgsystem')},
            },
        ),
        migrations.CreateModel(
            name='ThreatModelRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('depends_on', 'Depends On'), ('subsystem_of', 'Subsystem Of'), ('related_to', 'Related To'), ('superseded_by', 'Superseded By')], max_length=20)),
                ('source_threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='threat_models.threatmodel')),
                ('target_threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='threat_models.threatmodel')),
            ],
            options={
                'unique_together': {('source_threat_model', 'target_threat_model', 'relation_type')},
            },
        ),
    ]
