# Generated by Django 5.1.15 on 2026-03-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatmodel',
            name='modeling_mode',
        ),
    ]
