# Generated by Django 5.1.15 on 2026-03-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatmodel',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
