# Generated by Django 5.1.15 on 2026-03-04 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_models', '0002_threatmodel_format_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatmodel',
            name='scope_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='scope_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OutOfScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_of_scope_items', to='threat_models.threatmodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
