# Generated by Django 5.1.15 on 2026-07-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threat_models", "0003_threatmodellibrarypack"),
    ]

    operations = [
        migrations.CreateModel(
            name="UseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "flow_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured use case data: preconditions, postconditions, success_criteria, main_flow, alternative_flows, exceptions",
                    ),
                ),
                ("format_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="use_cases",
                        to="threat_models.threatmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
