# Generated by Django 5.1.15 on 2026-03-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threat_models", "0004_backfill_owning_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatmodel",
            name="assumptions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
