# Generated by Django 5.1.15 on 2026-03-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("threat_models", "0005_add_assumptions_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="threatmodel",
            name="previous_version",
        ),
        migrations.RemoveField(
            model_name="threatmodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="threatmodel",
            name="trigger",
        ),
        migrations.RemoveField(
            model_name="threatmodel",
            name="version",
        ),
    ]
