# Generated by Django 5.1.15 on 2026-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessunit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('organization', 'code'), name='unique_business_unit_code_per_org'),
        ),
    ]
