# Generated by Django 5.1.15 on 2026-03-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShadowUser",
        ),
    ]
