# Generated by Django 5.1.15 on 2026-03-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_remove_shadow_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("organization", "code"),
                name="unique_team_code_per_org",
            ),
        ),
    ]
