# Generated by Django 5.1.15 on 2026-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountermeasureLibraryStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sufficiency",
                    models.CharField(
                        choices=[("full", "Full"), ("partial", "Partial")],
                        default="partial",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StandardFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                ("issuer", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name", "version"],
            },
        ),
        migrations.CreateModel(
            name="StandardRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section_code", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["framework", "section_code"],
            },
        ),
    ]
