# Generated by Django 5.1.15 on 2026-03-22 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('packs', '0001_initial'),
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countermeasurelibrarystandard',
            name='countermeasure_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_mappings', to='threats.countermeasurelibrary'),
        ),
        migrations.AddField(
            model_name='standardframework',
            name='source_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frameworks', to='packs.librarypack'),
        ),
        migrations.AddField(
            model_name='standardrequirement',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='compliance.standardframework'),
        ),
        migrations.AddField(
            model_name='standardrequirement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='compliance.standardrequirement'),
        ),
        migrations.AddField(
            model_name='countermeasurelibrarystandard',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countermeasure_mappings', to='compliance.standardrequirement'),
        ),
        migrations.AlterUniqueTogether(
            name='countermeasurelibrarystandard',
            unique_together={('countermeasure_library', 'requirement')},
        ),
    ]
