# Generated by Django 5.1.15 on 2026-07-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_add_standard_requirement_mapping"),
        ("threat_models", "0004_cyclonedx_schema_enrichment"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardframework",
            name="threat_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Populated for user-created internal standards. NULL for global pack-sourced frameworks.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_frameworks",
                to="threat_models.threatmodel",
            ),
        ),
        migrations.AddField(
            model_name="standardrequirement",
            name="acceptance_criteria",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="standardrequirement",
            name="format_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="standardrequirement",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="standardrequirement",
            name="priority",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="standardrequirement",
            name="requirement_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="standardrequirement",
            name="status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
