# Generated by Django 5.1.15 on 2025-12-26 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagrams", "0001_initial"),
        ("organizations", "0001_initial"),
        ("systems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("pentest", "Penetration Test"),
                            ("auto", "Automated Scan"),
                            ("code_review", "Code Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("passed", models.BooleanField(default=False)),
                ("evidence", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComponentInstanceThreat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inherent_severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "residual_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("mitigated", "Mitigated"),
                            ("accepted", "Accepted"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("justification", models.TextField(blank=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threats",
                        to="systems.orgsystemcomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["component", "threat_library"],
            },
        ),
        migrations.CreateModel(
            name="CountermeasureLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("procedural", "Procedural"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means global/shared",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countermeasure_library",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countermeasure library",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComponentInstanceCountermeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("gap", "Gap"),
                            ("planned", "Planned"),
                            ("verified", "Verified"),
                            ("waived", "Waived"),
                        ],
                        default="gap",
                        max_length=20,
                    ),
                ),
                ("evidence_url", models.URLField(blank=True)),
                ("required_for_release", models.BooleanField(default=False)),
                (
                    "assigned_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_component_countermeasures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_component_countermeasures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance_threat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countermeasures",
                        to="threats.componentinstancethreat",
                    ),
                ),
                (
                    "countermeasure_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="component_instances",
                        to="threats.countermeasurelibrary",
                    ),
                ),
            ],
            options={
                "unique_together": {("instance_threat", "countermeasure_library")},
            },
        ),
        migrations.CreateModel(
            name="DataFlowInstanceThreat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inherent_severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "residual_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("mitigated", "Mitigated"),
                            ("accepted", "Accepted"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "data_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threats",
                        to="systems.dataflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlowInstanceCountermeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("gap", "Gap"),
                            ("planned", "Planned"),
                            ("verified", "Verified"),
                            ("waived", "Waived"),
                        ],
                        default="gap",
                        max_length=20,
                    ),
                ),
                ("evidence_url", models.URLField(blank=True)),
                ("required_for_release", models.BooleanField(default=False)),
                (
                    "assigned_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_flow_countermeasures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "countermeasure_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flow_instances",
                        to="threats.countermeasurelibrary",
                    ),
                ),
                (
                    "flow_threat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countermeasures",
                        to="threats.dataflowinstancethreat",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_flow_countermeasures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("flow_threat", "countermeasure_library")},
            },
        ),
        migrations.CreateModel(
            name="ThreatLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "stride_category",
                    models.CharField(
                        choices=[
                            ("spoofing", "Spoofing"),
                            ("tampering", "Tampering"),
                            ("repudiation", "Repudiation"),
                            ("information_disclosure", "Information Disclosure"),
                            ("denial_of_service", "Denial of Service"),
                            ("elevation_of_privilege", "Elevation of Privilege"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("stride", "STRIDE"),
                            ("capec", "CAPEC"),
                            ("owasp", "OWASP"),
                            ("cwe", "CWE"),
                            ("custom", "Custom"),
                        ],
                        default="stride",
                        max_length=20,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, help_text="e.g. CAPEC-66, CWE-89", max_length=50
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means global/shared",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_library",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Threat library",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PentestFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finding_description", models.TextField()),
                ("severity", models.CharField(max_length=20)),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("unpredicted", "Unpredicted"),
                            ("false_positive", "False Positive"),
                        ],
                        default="unpredicted",
                        max_length=20,
                    ),
                ),
                (
                    "matched_component_countermeasure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pentest_findings",
                        to="threats.componentinstancecountermeasure",
                    ),
                ),
                (
                    "matched_flow_countermeasure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pentest_findings",
                        to="threats.flowinstancecountermeasure",
                    ),
                ),
                (
                    "threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pentest_findings",
                        to="diagrams.threatmodel",
                    ),
                ),
                (
                    "matched_threat_library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_pentest_findings",
                        to="threats.threatlibrary",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="dataflowinstancethreat",
            name="threat_library",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flow_instances",
                to="threats.threatlibrary",
            ),
        ),
        migrations.AddField(
            model_name="componentinstancethreat",
            name="threat_library",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="component_instances",
                to="threats.threatlibrary",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dataflowinstancethreat",
            unique_together={("data_flow", "threat_library")},
        ),
        migrations.CreateModel(
            name="ComponentLibraryThreat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_severity", models.CharField(default="medium", max_length=20)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("component", "Component"),
                            ("flow", "Data Flow"),
                            ("both", "Both"),
                        ],
                        default="component",
                        max_length=20,
                    ),
                ),
                (
                    "component_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threats",
                        to="systems.componentlibrary",
                    ),
                ),
                (
                    "threat_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_associations",
                        to="threats.threatlibrary",
                    ),
                ),
            ],
            options={
                "unique_together": {("component_library", "threat_library")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="componentinstancethreat",
            unique_together={("component", "threat_library")},
        ),
    ]
