# Generated by Django 5.1.15 on 2026-03-01 14:48

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('packs', '0001_initial'),
        ('systems', '0001_initial'),
        ('threat_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('pentest', 'Penetration Test'), ('auto', 'Automated Scan'), ('code_review', 'Code Review')], max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('evidence', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentInstanceThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inherent_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('residual_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted')], default='open', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('is_dismissed', models.BooleanField(default=False, help_text='Dismissed threats are hidden from active view but preserved for audit')),
                ('dismissal_reason', models.TextField(blank=True, default='', help_text='Reason for dismissing the threat')),
                ('threat_name', models.CharField(blank=True, help_text='Copied from ThreatLibrary.name on creation', max_length=255)),
                ('threat_description', models.TextField(blank=True, help_text='Copied from ThreatLibrary.description on creation')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='systems.orgsystemcomponent')),
            ],
            options={
                'ordering': ['component', 'threat_library'],
            },
        ),
        migrations.CreateModel(
            name='CountermeasureLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text="Unique identifier within pack, e.g., 'encryption-at-rest'", max_length=100)),
                ('qualified_slug', models.CharField(blank=True, db_index=True, help_text="Namespace-safe identifier, e.g., 'security-controls/encryption-at-rest'", max_length=200, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('control_type', models.CharField(choices=[('technical', 'Technical'), ('procedural', 'Procedural')], max_length=20)),
                ('cost', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('customization_status', models.CharField(choices=[('original', 'Original (from pack)'), ('customized', 'Customized (user edited)'), ('detached', 'Detached (unlinked from pack)')], default='original', max_length=20)),
                ('base_item_qualified_slug', models.CharField(blank=True, db_index=True, help_text='Original item this was forked/customized from', max_length=200)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Previous slugs for backward compatibility', size=None)),
                ('source_pack', models.ForeignKey(blank=True, help_text='Pack this item came from (null = custom or legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countermeasures', to='packs.librarypack')),
            ],
            options={
                'verbose_name_plural': 'Countermeasure library',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentInstanceCountermeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('gap', 'Gap'), ('planned', 'Planned'), ('verified', 'Verified'), ('waived', 'Waived')], default='gap', max_length=20)),
                ('evidence_url', models.URLField(blank=True)),
                ('required_for_release', models.BooleanField(default=False)),
                ('countermeasure_name', models.CharField(blank=True, help_text='Copied from CountermeasureLibrary.name on creation', max_length=255)),
                ('countermeasure_description', models.TextField(blank=True, help_text='Copied from CountermeasureLibrary.description on creation')),
                ('control_type', models.CharField(blank=True, help_text='Copied from CountermeasureLibrary.control_type on creation', max_length=20)),
                ('effectiveness', models.FloatField(blank=True, help_text='User-assessed control effectiveness (0.0-1.0). Null = not yet assessed.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('assigned_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_component_countermeasures', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_component_countermeasures', to=settings.AUTH_USER_MODEL)),
                ('instance_threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countermeasures', to='threats.componentinstancethreat')),
                ('countermeasure_library', models.ForeignKey(blank=True, help_text='Null means orphaned/custom countermeasure (library item was removed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_instances', to='threats.countermeasurelibrary')),
            ],
            options={
                'unique_together': {('instance_threat', 'countermeasure_library')},
            },
        ),
        migrations.CreateModel(
            name='DataFlowInstanceThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inherent_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('residual_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted')], default='open', max_length=20)),
                ('is_dismissed', models.BooleanField(default=False, help_text='Dismissed threats are hidden from active view but preserved for audit')),
                ('dismissal_reason', models.TextField(blank=True, default='', help_text='Reason for dismissing the threat')),
                ('threat_name', models.CharField(blank=True, help_text='Copied from ThreatLibrary.name on creation', max_length=255)),
                ('threat_description', models.TextField(blank=True, help_text='Copied from ThreatLibrary.description on creation')),
                ('data_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='systems.dataflow')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('source_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomies', to='packs.librarypack')),
            ],
            options={
                'verbose_name_plural': 'External taxonomies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlowInstanceCountermeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('gap', 'Gap'), ('planned', 'Planned'), ('verified', 'Verified'), ('waived', 'Waived')], default='gap', max_length=20)),
                ('evidence_url', models.URLField(blank=True)),
                ('required_for_release', models.BooleanField(default=False)),
                ('countermeasure_name', models.CharField(blank=True, help_text='Copied from CountermeasureLibrary.name on creation', max_length=255)),
                ('countermeasure_description', models.TextField(blank=True, help_text='Copied from CountermeasureLibrary.description on creation')),
                ('control_type', models.CharField(blank=True, help_text='Copied from CountermeasureLibrary.control_type on creation', max_length=20)),
                ('effectiveness', models.FloatField(blank=True, help_text='User-assessed control effectiveness (0.0-1.0). Null = not yet assessed.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('assigned_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_flow_countermeasures', to=settings.AUTH_USER_MODEL)),
                ('countermeasure_library', models.ForeignKey(blank=True, help_text='Null means orphaned/custom countermeasure (library item was removed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_instances', to='threats.countermeasurelibrary')),
                ('flow_threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countermeasures', to='threats.dataflowinstancethreat')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_flow_countermeasures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flow_threat', 'countermeasure_library')},
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scoring_metadata', models.JSONField(default=dict)),
                ('inherent_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('inherent_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('residual_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('residual_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('format_metadata', models.JSONField(default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_risks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='threat_models.threatmodel')),
            ],
            options={
                'ordering': ['-inherent_score'],
            },
        ),
        migrations.CreateModel(
            name='RiskThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_links', to='threats.componentinstancethreat')),
                ('flow_threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_links', to='threats.dataflowinstancethreat')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_threats', to='threats.risk')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text="Normalized ID: 'tampering', '66', 'CWE-89', 'T1059'", max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='threats.externaltaxonomy')),
            ],
            options={
                'ordering': ['taxonomy', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='ThreatLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text="Unique identifier within pack, e.g., 'sql-injection'", max_length=100)),
                ('qualified_slug', models.CharField(blank=True, db_index=True, help_text="Namespace-safe identifier, e.g., 'owasp-top10/sql-injection'", max_length=200, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('customization_status', models.CharField(choices=[('original', 'Original (from pack)'), ('customized', 'Customized (user edited)'), ('detached', 'Detached (unlinked from pack)')], default='original', max_length=20)),
                ('base_item_qualified_slug', models.CharField(blank=True, db_index=True, help_text='Original item this was forked/customized from', max_length=200)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Previous slugs for backward compatibility', size=None)),
                ('source_pack', models.ForeignKey(blank=True, help_text='Pack this item came from (null = custom or legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threats', to='packs.librarypack')),
            ],
            options={
                'verbose_name_plural': 'Threat library',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PentestFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding_description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('reconciliation_status', models.CharField(choices=[('matched', 'Matched'), ('unpredicted', 'Unpredicted'), ('false_positive', 'False Positive')], default='unpredicted', max_length=20)),
                ('matched_component_countermeasure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pentest_findings', to='threats.componentinstancecountermeasure')),
                ('matched_flow_countermeasure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pentest_findings', to='threats.flowinstancecountermeasure')),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pentest_findings', to='threat_models.threatmodel')),
                ('matched_threat_library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_pentest_findings', to='threats.threatlibrary')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dataflowinstancethreat',
            name='threat_library',
            field=models.ForeignKey(blank=True, help_text='Null means orphaned/custom threat (library item was removed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_instances', to='threats.threatlibrary'),
        ),
        migrations.AddField(
            model_name='countermeasurelibrary',
            name='applicable_threats',
            field=models.ManyToManyField(blank=True, help_text='Threats this countermeasure can mitigate', related_name='applicable_countermeasures', to='threats.threatlibrary'),
        ),
        migrations.CreateModel(
            name='ComponentLibraryThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_severity', models.CharField(default='medium', max_length=20)),
                ('applies_to', models.CharField(choices=[('component', 'Component'), ('flow', 'Data Flow'), ('both', 'Both')], default='component', max_length=20)),
                ('component_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='systems.componentlibrary')),
                ('threat_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_associations', to='threats.threatlibrary')),
            ],
        ),
        migrations.AddField(
            model_name='componentinstancethreat',
            name='threat_library',
            field=models.ForeignKey(blank=True, help_text='Null means orphaned/custom threat (library item was removed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_instances', to='threats.threatlibrary'),
        ),
        migrations.CreateModel(
            name='ThreatLibraryTaxonomyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxonomy_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_libraries', to='threats.taxonomyentry')),
                ('threat_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_entries', to='threats.threatlibrary')),
            ],
        ),
        migrations.CreateModel(
            name='FlowInstanceCountermeasureTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('flow_countermeasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='threats.flowinstancecountermeasure')),
                ('verification_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_countermeasure_tests', to='threats.verificationtest')),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentInstanceCountermeasureTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('component_countermeasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='threats.componentinstancecountermeasure')),
                ('verification_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_countermeasure_tests', to='threats.verificationtest')),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentInstanceCountermeasureStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sufficiency', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], default='partial', max_length=10)),
                ('component_countermeasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_standard_mappings', to='threats.componentinstancecountermeasure')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_instance_countermeasure_mappings', to='compliance.standardrequirement')),
            ],
            options={
                'verbose_name': 'Component countermeasure compliance mapping',
                'verbose_name_plural': 'Component countermeasure compliance mappings',
                'unique_together': {('component_countermeasure', 'requirement')},
            },
        ),
        migrations.CreateModel(
            name='FlowInstanceCountermeasureStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sufficiency', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], default='partial', max_length=10)),
                ('flow_countermeasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_standard_mappings', to='threats.flowinstancecountermeasure')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_instance_countermeasure_mappings', to='compliance.standardrequirement')),
            ],
            options={
                'verbose_name': 'Flow countermeasure compliance mapping',
                'verbose_name_plural': 'Flow countermeasure compliance mappings',
                'unique_together': {('flow_countermeasure', 'requirement')},
            },
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.UniqueConstraint(fields=('threat_model', 'name'), name='unique_risk_per_threat_model'),
        ),
        migrations.AddConstraint(
            model_name='riskthreat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('component_threat__isnull', False), ('flow_threat__isnull', True)), models.Q(('component_threat__isnull', True), ('flow_threat__isnull', False)), _connector='OR'), name='risk_threat_exactly_one_fk'),
        ),
        migrations.AddConstraint(
            model_name='riskthreat',
            constraint=models.UniqueConstraint(condition=models.Q(('component_threat__isnull', False)), fields=('risk', 'component_threat'), name='unique_risk_component_threat'),
        ),
        migrations.AddConstraint(
            model_name='riskthreat',
            constraint=models.UniqueConstraint(condition=models.Q(('flow_threat__isnull', False)), fields=('risk', 'flow_threat'), name='unique_risk_flow_threat'),
        ),
        migrations.AlterUniqueTogether(
            name='taxonomyentry',
            unique_together={('taxonomy', 'external_id')},
        ),
        migrations.AddConstraint(
            model_name='threatlibrary',
            constraint=models.UniqueConstraint(fields=('qualified_slug',), name='unique_threat_qualified_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='dataflowinstancethreat',
            unique_together={('data_flow', 'threat_library')},
        ),
        migrations.AddConstraint(
            model_name='countermeasurelibrary',
            constraint=models.UniqueConstraint(fields=('qualified_slug',), name='unique_countermeasure_qualified_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='componentlibrarythreat',
            unique_together={('component_library', 'threat_library')},
        ),
        migrations.AlterUniqueTogether(
            name='componentinstancethreat',
            unique_together={('component', 'threat_library')},
        ),
        migrations.AlterUniqueTogether(
            name='threatlibrarytaxonomyentry',
            unique_together={('threat_library', 'taxonomy_entry')},
        ),
        migrations.AlterUniqueTogether(
            name='flowinstancecountermeasuretest',
            unique_together={('flow_countermeasure', 'verification_test')},
        ),
        migrations.AlterUniqueTogether(
            name='componentinstancecountermeasuretest',
            unique_together={('component_countermeasure', 'verification_test')},
        ),
    ]
