# Generated by Django 5.1.15 on 2026-03-22 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_initial'),
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstancecountermeasurestandard',
            name='framework_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='componentinstancecountermeasurestandard',
            name='requirement_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='componentinstancecountermeasurestandard',
            name='section_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='componentinstancethreat',
            name='taxonomy_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of taxonomy entries at creation time'),
        ),
        migrations.AddField(
            model_name='dataflowinstancethreat',
            name='taxonomy_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of taxonomy entries at creation time'),
        ),
        migrations.AddField(
            model_name='flowinstancecountermeasurestandard',
            name='framework_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flowinstancecountermeasurestandard',
            name='requirement_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='flowinstancecountermeasurestandard',
            name='section_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='componentinstancecountermeasurestandard',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_instance_countermeasure_mappings', to='compliance.standardrequirement'),
        ),
        migrations.AlterField(
            model_name='flowinstancecountermeasurestandard',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_instance_countermeasure_mappings', to='compliance.standardrequirement'),
        ),
    ]
