# Generated by Django 5.1.15 on 2026-01-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentinstancethreat",
            name="dismissal_reason",
            field=models.TextField(
                blank=True, default="", help_text="Reason for dismissing the threat"
            ),
        ),
        migrations.AddField(
            model_name="componentinstancethreat",
            name="is_dismissed",
            field=models.BooleanField(
                default=False,
                help_text="Dismissed threats are hidden from active view but preserved for audit",
            ),
        ),
        migrations.AddField(
            model_name="dataflowinstancethreat",
            name="dismissal_reason",
            field=models.TextField(
                blank=True, default="", help_text="Reason for dismissing the threat"
            ),
        ),
        migrations.AddField(
            model_name="dataflowinstancethreat",
            name="is_dismissed",
            field=models.BooleanField(
                default=False,
                help_text="Dismissed threats are hidden from active view but preserved for audit",
            ),
        ),
    ]
