# Generated by Django 5.1.15 on 2026-03-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstancecountermeasure',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='componentinstancecountermeasure',
            name='priority',
            field=models.CharField(blank=True, default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='componentinstancethreat',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dataflowinstancethreat',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='flowinstancecountermeasure',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='flowinstancecountermeasure',
            name='priority',
            field=models.CharField(blank=True, default='none', max_length=10),
        ),
    ]
