# Generated by Django 5.1.15 on 2026-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0002_componentinstancecountermeasurestandard_framework_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentinstancecountermeasure',
            options={'ordering': ['instance_threat', 'display_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='componentinstancethreat',
            options={'ordering': ['component', 'display_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='dataflowinstancethreat',
            options={'ordering': ['data_flow', 'display_order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='flowinstancecountermeasure',
            options={'ordering': ['flow_threat', 'display_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='componentinstancecountermeasure',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='componentinstancethreat',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataflowinstancethreat',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flowinstancecountermeasure',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
