# Generated by Django 5.1.15 on 2026-03-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0002_componentinstancecountermeasure_format_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentinstancecountermeasure",
            name="status",
            field=models.CharField(
                choices=[
                    ("gap", "Gap"),
                    ("planned", "Planned"),
                    ("verified", "Verified"),
                    ("waived", "Waived"),
                    ("platform", "Platform"),
                ],
                default="gap",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flowinstancecountermeasure",
            name="status",
            field=models.CharField(
                choices=[
                    ("gap", "Gap"),
                    ("planned", "Planned"),
                    ("verified", "Verified"),
                    ("waived", "Waived"),
                    ("platform", "Platform"),
                ],
                default="gap",
                max_length=20,
            ),
        ),
    ]
