# Generated by Django 5.1.15 on 2026-01-30 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_initial"),
        ("threats", "0002_add_threat_dismiss_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentInstanceCountermeasureStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sufficiency",
                    models.CharField(
                        choices=[("full", "Full"), ("partial", "Partial")],
                        default="partial",
                        max_length=10,
                    ),
                ),
                (
                    "component_countermeasure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_standard_mappings",
                        to="threats.componentinstancecountermeasure",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_instance_countermeasure_mappings",
                        to="compliance.standardrequirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component countermeasure compliance mapping",
                "verbose_name_plural": "Component countermeasure compliance mappings",
                "unique_together": {("component_countermeasure", "requirement")},
            },
        ),
        migrations.CreateModel(
            name="FlowInstanceCountermeasureStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sufficiency",
                    models.CharField(
                        choices=[("full", "Full"), ("partial", "Partial")],
                        default="partial",
                        max_length=10,
                    ),
                ),
                (
                    "flow_countermeasure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_standard_mappings",
                        to="threats.flowinstancecountermeasure",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_instance_countermeasure_mappings",
                        to="compliance.standardrequirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow countermeasure compliance mapping",
                "verbose_name_plural": "Flow countermeasure compliance mappings",
                "unique_together": {("flow_countermeasure", "requirement")},
            },
        ),
    ]
