# Generated by Django 5.1.15 on 2025-12-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("threats", "0002_countermeasurelibrary_source_pack_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countermeasurelibrary",
            name="applicable_threats",
            field=models.ManyToManyField(
                blank=True,
                help_text="Threats this countermeasure can mitigate",
                related_name="applicable_countermeasures",
                to="threats.threatlibrary",
            ),
        ),
        migrations.AddField(
            model_name="verificationtest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Null means global/shared test",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_tests",
                to="organizations.organization",
            ),
        ),
        migrations.CreateModel(
            name="ComponentInstanceCountermeasureTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component_countermeasure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="threats.componentinstancecountermeasure",
                    ),
                ),
                (
                    "verification_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_countermeasure_tests",
                        to="threats.verificationtest",
                    ),
                ),
            ],
            options={
                "ordering": ["-tested_at"],
                "unique_together": {("component_countermeasure", "verification_test")},
            },
        ),
        migrations.CreateModel(
            name="FlowInstanceCountermeasureTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flow_countermeasure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="threats.flowinstancecountermeasure",
                    ),
                ),
                (
                    "verification_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_countermeasure_tests",
                        to="threats.verificationtest",
                    ),
                ),
            ],
            options={
                "ordering": ["-tested_at"],
                "unique_together": {("flow_countermeasure", "verification_test")},
            },
        ),
    ]
