# Generated by Django 5.1.15 on 2026-03-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0003_alter_componentinstancecountermeasure_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentinstancethreat",
            name="status",
            field=models.CharField(
                choices=[
                    ("exposed", "Exposed"),
                    ("addressable", "Addressable"),
                    ("mitigated", "Mitigated"),
                ],
                default="exposed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dataflowinstancethreat",
            name="status",
            field=models.CharField(
                choices=[
                    ("exposed", "Exposed"),
                    ("addressable", "Addressable"),
                    ("mitigated", "Mitigated"),
                ],
                default="exposed",
                max_length=20,
            ),
        ),
    ]
