# Generated by Django 5.1.15 on 2026-02-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0003_alter_librarypack_pack_type"),
        ("threats", "0003_add_threat_model_and_instance_compliance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalTaxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("version", models.CharField(blank=True, max_length=20)),
                (
                    "source_pack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taxonomies",
                        to="packs.librarypack",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "External taxonomies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaxonomyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        help_text="Normalized ID: 'tampering', '66', 'CWE-89', 'T1059'",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="threats.externaltaxonomy",
                    ),
                ),
            ],
            options={
                "ordering": ["taxonomy", "external_id"],
                "unique_together": {("taxonomy", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="ThreatLibraryTaxonomyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "taxonomy_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_libraries",
                        to="threats.taxonomyentry",
                    ),
                ),
                (
                    "threat_library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomy_entries",
                        to="threats.threatlibrary",
                    ),
                ),
            ],
            options={
                "unique_together": {("threat_library", "taxonomy_entry")},
            },
        ),
    ]
