# Generated by Django 5.1.15 on 2025-12-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0003_schema_discrepancy_fixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="countermeasurelibrary",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique identifier for pack references, e.g., 'encryption-at-rest'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="threatlibrary",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique identifier for pack references, e.g., 'sql-injection'",
                max_length=100,
            ),
        ),
    ]
