# Generated by Django 5.1.15 on 2025-12-27 11:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0004_add_slug_to_library_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="countermeasurelibrary",
            name="aliases",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Previous slugs for backward compatibility",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="countermeasurelibrary",
            name="base_item_qualified_slug",
            field=models.CharField(
                blank=True,
                help_text="Original item this was forked/customized from",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="countermeasurelibrary",
            name="customization_status",
            field=models.CharField(
                choices=[
                    ("original", "Original (from pack)"),
                    ("customized", "Customized (org edited)"),
                    ("detached", "Detached (unlinked from pack)"),
                ],
                default="original",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="countermeasurelibrary",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="countermeasurelibrary",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="countermeasurelibrary",
            name="qualified_slug",
            field=models.CharField(
                blank=True,
                help_text="Namespace-safe identifier, e.g., 'security-controls/encryption-at-rest'",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="threatlibrary",
            name="aliases",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Previous slugs for backward compatibility",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="threatlibrary",
            name="base_item_qualified_slug",
            field=models.CharField(
                blank=True,
                help_text="Original item this was forked/customized from",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="threatlibrary",
            name="customization_status",
            field=models.CharField(
                choices=[
                    ("original", "Original (from pack)"),
                    ("customized", "Customized (org edited)"),
                    ("detached", "Detached (unlinked from pack)"),
                ],
                default="original",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="threatlibrary",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="threatlibrary",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="threatlibrary",
            name="qualified_slug",
            field=models.CharField(
                blank=True,
                help_text="Namespace-safe identifier, e.g., 'owasp-top10/sql-injection'",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="countermeasurelibrary",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique identifier within pack, e.g., 'encryption-at-rest'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="threatlibrary",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique identifier within pack, e.g., 'sql-injection'",
                max_length=100,
            ),
        ),
    ]
