# Generated by Django 5.1.15 on 2026-03-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0004_alter_componentinstancethreat_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countermeasurelibrary',
            name='default_status',
            field=models.CharField(choices=[('gap', 'Gap'), ('platform', 'Platform')], default='gap', max_length=20),
        ),
        migrations.AlterField(
            model_name='countermeasurelibrary',
            name='control_type',
            field=models.CharField(default='preventive', max_length=50),
        ),
    ]
