# Generated by Django 5.1.15 on 2026-02-28 13:54

from django.db import migrations


def seed_stride_and_populate(apps, schema_editor):
    ExternalTaxonomy = apps.get_model("threats", "ExternalTaxonomy")
    TaxonomyEntry = apps.get_model("threats", "TaxonomyEntry")
    ThreatLibrary = apps.get_model("threats", "ThreatLibrary")
    ThreatLibraryTaxonomyEntry = apps.get_model("threats", "ThreatLibraryTaxonomyEntry")

    # Create STRIDE taxonomy
    stride = ExternalTaxonomy.objects.create(
        slug="stride",
        name="STRIDE Threat Model",
        description="Microsoft STRIDE threat classification",
        source_url="https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool-threats",
    )

    # Create 6 STRIDE entries (kebab-case IDs)
    entries = {
        "spoofing": "Spoofing",
        "tampering": "Tampering",
        "repudiation": "Repudiation",
        "information-disclosure": "Information Disclosure",
        "denial-of-service": "Denial of Service",
        "elevation-of-privilege": "Elevation of Privilege",
    }
    entry_objects = {}
    for entry_id, title in entries.items():
        entry_objects[entry_id] = TaxonomyEntry.objects.create(
            taxonomy=stride,
            external_id=entry_id,
            title=title,
        )

    # Map old camelCase/snake_case values to new kebab-case IDs
    old_to_new = {
        "spoofing": "spoofing",
        "tampering": "tampering",
        "repudiation": "repudiation",
        "informationDisclosure": "information-disclosure",
        "information_disclosure": "information-disclosure",
        "denialOfService": "denial-of-service",
        "denial_of_service": "denial-of-service",
        "elevationOfPrivilege": "elevation-of-privilege",
        "elevation_of_privilege": "elevation-of-privilege",
    }

    # Populate M2M for all existing ThreatLibrary records
    for threat in ThreatLibrary.objects.exclude(stride_category=""):
        new_id = old_to_new.get(threat.stride_category)
        if new_id and new_id in entry_objects:
            ThreatLibraryTaxonomyEntry.objects.get_or_create(
                threat_library=threat,
                taxonomy_entry=entry_objects[new_id],
            )


def reverse_seed(apps, schema_editor):
    """Remove seeded data on reverse migration."""
    ExternalTaxonomy = apps.get_model("threats", "ExternalTaxonomy")
    ExternalTaxonomy.objects.filter(slug="stride").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0004_externaltaxonomy_taxonomyentry_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_stride_and_populate, reverse_seed),
    ]
