# Generated by Django 5.1.15 on 2026-05-31 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0005_threatpersona_threatsource_remove_threat_actor_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="componentinstancecountermeasure",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Target completion date", null=True
            ),
        ),
        migrations.AddField(
            model_name="componentinstancecountermeasure",
            name="external_ticket_url",
            field=models.URLField(
                blank=True, help_text="Link to Jira/GitHub/etc. ticket"
            ),
        ),
        migrations.AddField(
            model_name="flowinstancecountermeasure",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Target completion date", null=True
            ),
        ),
        migrations.AddField(
            model_name="flowinstancecountermeasure",
            name="external_ticket_url",
            field=models.URLField(
                blank=True, help_text="Link to Jira/GitHub/etc. ticket"
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="auto_populated",
            field=models.BooleanField(
                default=False,
                help_text="True if this risk was auto-populated from an exposed threat",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Target date for risk resolution", null=True
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="impact",
            field=models.IntegerField(
                blank=True,
                help_text="Impact score 1-5",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="likelihood",
            field=models.IntegerField(
                blank=True,
                help_text="Likelihood score 1-5",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("mitigated", "Mitigated"),
                    ("accepted", "Accepted"),
                    ("closed", "Closed"),
                ],
                default="open",
                help_text="Explicit lifecycle status of this risk",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="componentinstancecountermeasure",
            name="status",
            field=models.CharField(
                choices=[
                    ("gap", "Gap"),
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("verified", "Verified"),
                    ("waived", "Waived"),
                    ("platform", "Platform"),
                ],
                default="gap",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flowinstancecountermeasure",
            name="status",
            field=models.CharField(
                choices=[
                    ("gap", "Gap"),
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("verified", "Verified"),
                    ("waived", "Waived"),
                    ("platform", "Platform"),
                ],
                default="gap",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CountermeasureComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("change_summary", models.CharField(blank=True, max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="countermeasure_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "component_countermeasure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="threats.componentinstancecountermeasure",
                    ),
                ),
                (
                    "flow_countermeasure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="threats.flowinstancecountermeasure",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("component_countermeasure__isnull", False),
                                ("flow_countermeasure__isnull", True),
                            ),
                            models.Q(
                                ("component_countermeasure__isnull", True),
                                ("flow_countermeasure__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="countermeasure_comment_exactly_one_fk",
                    )
                ],
            },
        ),
    ]
