# Generated by Django 5.1.15 on 2025-12-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("packs", "0002_reviewer_feedback_fixes"),
        ("threats", "0005_reviewer_feedback_fixes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countermeasurelibrary",
            name="base_item_qualified_slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Original item this was forked/customized from",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="countermeasurelibrary",
            name="qualified_slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Namespace-safe identifier, e.g., 'security-controls/encryption-at-rest'",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="threatlibrary",
            name="base_item_qualified_slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Original item this was forked/customized from",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="threatlibrary",
            name="qualified_slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Namespace-safe identifier, e.g., 'owasp-top10/sql-injection'",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="countermeasurelibrary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("qualified_slug",),
                name="unique_active_countermeasure_qualified_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="threatlibrary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("qualified_slug",),
                name="unique_active_threat_qualified_slug",
            ),
        ),
    ]
