# Generated by Django 5.1.15 on 2026-03-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0005_countermeasurelibrary_default_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentinstancecountermeasure",
            name="control_type",
            field=models.CharField(
                blank=True,
                help_text="Copied from CountermeasureLibrary.control_type on creation",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="flowinstancecountermeasure",
            name="control_type",
            field=models.CharField(
                blank=True,
                help_text="Copied from CountermeasureLibrary.control_type on creation",
                max_length=50,
            ),
        ),
    ]
