# Generated by Django 5.1.15 on 2026-02-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0005_seed_stride_and_populate_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="componentinstancethreat",
            name="stride_category",
        ),
        migrations.RemoveField(
            model_name="dataflowinstancethreat",
            name="stride_category",
        ),
        migrations.RemoveField(
            model_name="threatlibrary",
            name="source",
        ),
        migrations.RemoveField(
            model_name="threatlibrary",
            name="source_id",
        ),
        migrations.RemoveField(
            model_name="threatlibrary",
            name="stride_category",
        ),
    ]
