# Generated by Django 5.1.15 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0006_widen_instance_control_type_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentinstancecountermeasure",
            name="is_inherited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="componentinstancecountermeasure",
            name="inherited_from_component_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="componentinstancecountermeasure",
            name="inherited_from_zone_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="flowinstancecountermeasure",
            name="is_inherited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flowinstancecountermeasure",
            name="inherited_from_component_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="flowinstancecountermeasure",
            name="inherited_from_zone_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
