# Generated by Django 5.1.15 on 2025-12-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0006_zombie_record_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threatlibrary",
            name="stride_category",
            field=models.CharField(
                choices=[
                    ("spoofing", "Spoofing"),
                    ("tampering", "Tampering"),
                    ("repudiation", "Repudiation"),
                    ("informationDisclosure", "Information Disclosure"),
                    ("denialOfService", "Denial of Service"),
                    ("elevationOfPrivilege", "Elevation of Privilege"),
                ],
                max_length=30,
            ),
        ),
    ]
