# Generated by Django 5.1.15 on 2026-03-01 12:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagrams", "0005_remove_dfdtemplateslibrary_category_choices"),
        ("threats", "0006_drop_old_stride_and_source_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="componentinstancecountermeasure",
            name="effectiveness",
            field=models.FloatField(
                blank=True,
                help_text="User-assessed control effectiveness (0.0-1.0). Null = not yet assessed.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="flowinstancecountermeasure",
            name="effectiveness",
            field=models.FloatField(
                blank=True,
                help_text="User-assessed control effectiveness (0.0-1.0). Null = not yet assessed.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "scoring_method",
                    models.CharField(
                        choices=[
                            ("tm_library", "Likelihood x Impact (5x5 Matrix)"),
                            ("fair", "FAIR"),
                            ("owasp_rr", "OWASP Risk Rating"),
                            ("mozilla_rra", "Mozilla Rapid Risk Assessment"),
                            ("custom", "Manual Score"),
                        ],
                        default="tm_library",
                        max_length=20,
                    ),
                ),
                ("scoring_metadata", models.JSONField(default=dict)),
                (
                    "inherent_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "inherent_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "residual_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "residual_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("format_metadata", models.JSONField(default=dict)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "threat_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="diagrams.threatmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-inherent_score"],
            },
        ),
        migrations.CreateModel(
            name="RiskThreat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component_threat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_links",
                        to="threats.componentinstancethreat",
                    ),
                ),
                (
                    "flow_threat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_links",
                        to="threats.dataflowinstancethreat",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_threats",
                        to="threats.risk",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="risk",
            constraint=models.UniqueConstraint(
                fields=("threat_model", "name"), name="unique_risk_per_threat_model"
            ),
        ),
        migrations.AddConstraint(
            model_name="riskthreat",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("component_threat__isnull", False),
                        ("flow_threat__isnull", True),
                    ),
                    models.Q(
                        ("component_threat__isnull", True),
                        ("flow_threat__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="risk_threat_exactly_one_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskthreat",
            constraint=models.UniqueConstraint(
                condition=models.Q(("component_threat__isnull", False)),
                fields=("risk", "component_threat"),
                name="unique_risk_component_threat",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskthreat",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flow_threat__isnull", False)),
                fields=("risk", "flow_threat"),
                name="unique_risk_flow_threat",
            ),
        ),
    ]
