# Generated by Django 5.1.15 on 2026-06-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0006_add_mitigation_tracking_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="risk",
            name="auto_populated",
        ),
    ]
