# Generated by Django 5.1.15 on 2026-06-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0007_remove_auto_populated_from_risk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="risk",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="risk",
            name="impact",
        ),
        migrations.RemoveField(
            model_name="risk",
            name="likelihood",
        ),
        migrations.RemoveField(
            model_name="risk",
            name="status",
        ),
        migrations.AddField(
            model_name="risk",
            name="response",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accept", "Accept"),
                    ("mitigate", "Mitigate"),
                    ("transfer", "Transfer"),
                    ("avoid", "Avoid"),
                ],
                help_text="Risk response strategy per NIST IR 8286",
                max_length=20,
                null=True,
            ),
        ),
    ]
