# Generated by Django 5.1.15 on 2026-03-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0007_componentinstancecountermeasure_effectiveness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='scoring_method',
        ),
    ]
