# Generated by Django 5.1.15 on 2026-03-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0007_add_inherited_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="componentinstancethreat",
            name="justification",
        ),
        migrations.AddField(
            model_name="componentinstancethreat",
            name="severity_scoring_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dataflowinstancethreat",
            name="severity_scoring_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
