# Generated by Django 5.1.15 on 2026-03-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0008_remove_componentinstancethreat_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomyentry',
            name='reference_url',
            field=models.URLField(blank=True),
        ),
    ]
