# Generated by Django 5.1.15 on 2026-07-03 07:15

from django.db import migrations, models


def migrate_in_progress_to_planned(apps, schema_editor):
    InstanceCountermeasure = apps.get_model("threats", "InstanceCountermeasure")
    InstanceCountermeasure.objects.filter(status="in_progress").update(status="planned")


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0010_unify_countermeasure_models"),
    ]

    operations = [
        migrations.RunPython(migrate_in_progress_to_planned, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="instancecountermeasure",
            name="status",
            field=models.CharField(
                choices=[
                    ("gap", "Gap"),
                    ("planned", "Planned"),
                    ("verified", "Verified"),
                    ("waived", "Waived"),
                    ("platform", "Platform"),
                ],
                default="gap",
                max_length=20,
            ),
        ),
    ]
