# Generated by Django 5.1.15 on 2026-07-11 00:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threats", "0011_remove_in_progress_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="componentinstancethreat",
            name="access_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("external", "External"),
                    ("internal", "Internal"),
                    ("privileged", "Privileged"),
                    ("physical", "Physical"),
                ],
                default="",
                help_text="Access level required: none, external, internal, privileged, or physical",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="componentinstancethreat",
            name="intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accidental", "Accidental"),
                    ("opportunistic", "Opportunistic"),
                    ("targeted", "Targeted"),
                    ("persistent", "Persistent"),
                ],
                default="",
                help_text="Attacker intent: accidental, opportunistic, targeted, or persistent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dataflowinstancethreat",
            name="access_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("external", "External"),
                    ("internal", "Internal"),
                    ("privileged", "Privileged"),
                    ("physical", "Physical"),
                ],
                default="",
                help_text="Access level required: none, external, internal, privileged, or physical",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dataflowinstancethreat",
            name="intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accidental", "Accidental"),
                    ("opportunistic", "Opportunistic"),
                    ("targeted", "Targeted"),
                    ("persistent", "Persistent"),
                ],
                default="",
                help_text="Attacker intent: accidental, opportunistic, targeted, or persistent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="domains",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Risk domains, e.g. ['security', 'compliance']",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="target_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                help_text="Target risk level after planned mitigations",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="target_score",
            field=models.IntegerField(
                blank=True,
                help_text="Target risk score after planned mitigations",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="instancecountermeasure",
            name="status",
            field=models.CharField(
                choices=[
                    ("gap", "Gap"),
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("implemented", "Implemented"),
                    ("verified", "Verified"),
                    ("waived", "Waived"),
                    ("platform", "Platform"),
                    ("decommissioned", "Decommissioned"),
                ],
                default="gap",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RiskResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("avoid", "Avoid"),
                            ("reduce", "Reduce"),
                            ("transfer", "Transfer"),
                            ("accept", "Accept"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("implemented", "Implemented"),
                            ("verified", "Verified"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "effectiveness",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("cost", models.CharField(blank=True, max_length=20)),
                ("priority", models.CharField(blank=True, max_length=20)),
                ("target_date", models.DateTimeField(blank=True, null=True)),
                ("format_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_risk_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="threats.risk",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
